# Generated by Django 4.0.2 on 2023-07-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_userperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperfil',
            name='foto',
            field=models.ImageField(blank=True, default='blank/default.png', upload_to='uploads/profile_pictures'),
        ),
    ]
