# Generated by Django 4.0.2 on 2023-07-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_userperfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userperfil',
            old_name='aniversaio',
            new_name='aniversario',
        ),
    ]
