# Generated by Django 4.0.2 on 2023-07-02 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0004_rename_aniversaio_userperfil_aniversario'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperfil',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='seguidores', to=settings.AUTH_USER_MODEL),
        ),
    ]
