# Generated by Django 4.0.2 on 2023-07-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperfil',
            name='foto',
            field=models.ImageField(blank=True, default='media/uploads/profile_pictures/default.png', upload_to='media/uploads/profile_pictures'),
        ),
    ]
