# Generated by Django 4.0.2 on 2023-07-03 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_conexaomodel_alter_post_image_mensagemmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagemmodel',
            name='image',
        ),
    ]
