# Generated by Django 4.0.2 on 2023-07-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_remove_mensagemmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/post_images'),
        ),
        migrations.AlterField(
            model_name='userperfil',
            name='foto',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/default.png', upload_to='uploads/profile_pictures'),
        ),
    ]
