# Generated by Django 4.0.2 on 2023-02-14 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_artista_gestor_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='dataNasc',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='email',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='nome',
        ),
    ]
