# Generated by Django 4.0.2 on 2023-02-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_artista_datanasc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='dataNasc',
        ),
    ]
