# Generated by Django 4.0.2 on 2023-02-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_evento_fotocapaevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
