# Generated by Django 4.0.2 on 2023-02-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='date published')),
                ('horario', models.IntegerField(default=0)),
                ('visualizacao', models.IntegerField(default=0)),
            ],
        ),
    ]
