# Generated by Django 4.0.2 on 2023-02-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=1000)),
                ('legenda', models.CharField(max_length=1000)),
                ('curtida', models.IntegerField()),
                ('midia', models.IntegerField()),
            ],
        ),
    ]
