# Generated by Django 4.0.2 on 2023-02-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_artista_datanasc_remove_artista_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='nome',
            field=models.CharField(default='Ana', max_length=100),
        ),
    ]
