# Generated by Django 4.0.2 on 2023-02-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_artista_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='email',
            field=models.EmailField(default='anabia@gmail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='artista',
            name='profileing',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_images'),
        ),
        migrations.DeleteModel(
            name='Gestor',
        ),
    ]
