# Generated by Django 4.0.2 on 2023-02-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_artista_datanasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='dataNasc',
            field=models.DateTimeField(),
        ),
    ]
