# Generated by Django 4.0.2 on 2023-07-09 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('social', '0002_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPerfil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('nome', models.CharField(blank=True, max_length=30, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('aniversário', models.DateField(blank=True, null=True)),
                ('localização', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, default='uploads/profile_pictures/default.png', upload_to='uploads/profile_pictures')),
            ],
        ),
    ]
