# Generated by Django 4.0.2 on 2023-07-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_conexaomodel_mensagemmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperfil',
            name='bio',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
