# Generated by Django 4.0.2 on 2023-02-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='date published')),
                ('local', models.CharField(max_length=100)),
                ('nomeEvento', models.CharField(max_length=100)),
                ('biografiaEvento', models.CharField(max_length=500)),
            ],
        ),
    ]
